iqb-berlin/studio-lite

apps/api/src/app/admin/settings/setting.controller.ts
apps/api/src/app/database/entities/setting.entity.ts
apps/api/src/app/database/services/setting.service.ts
apps/api/src/main.ts
apps/frontend/src/app/admin/admin.module.ts
apps/frontend/src/app/admin/backend.service.ts
apps/frontend/src/app/admin/settings/app-config.component.html
apps/frontend/src/app/admin/settings/app-config.component.ts
apps/frontend/src/app/admin/settings/app-logo.component.html
apps/frontend/src/app/admin/settings/app-logo.component.ts
apps/frontend/src/app/admin/settings/settings.component.ts
apps/frontend/src/app/app.classes.ts
apps/frontend/src/app/app.component.html
apps/frontend/src/app/app.component.ts
apps/frontend/src/app/app.service.ts
apps/frontend/src/app/backend.service.ts
apps/frontend/src/app/home/about.component.ts
apps/frontend/src/app/home/home.component.css
libs/api-dto/src/index.ts
libs/api-dto/src/lib/dto/setting/app-logo-dto.ts
libs/api-dto/src/lib/dto/setting/config-dto.ts

- introduce new key 'app-logo' to settings table in database
- add css variable to customize background colors
- add upload of logo as base64 image into settinggs table

Add logo and color to application settings

---

apps/api/src/app/workspace/unit-download.class.ts
package-lock.json

- Add empty Definition tag when unit has no definition

Prevent empty unit definition file

---

apps/api/src/app/workspace/unit-download.class.ts
apps/frontend/src/app/workspace/dialogs/edit-settings.component.ts
apps/frontend/src/app/workspace/dialogs/export-unit.component.html
apps/frontend/src/app/workspace/dialogs/export-unit.component.ts
apps/frontend/src/assets/i18n/de.json
libs/api-dto/src/lib/dto/unit/unit-download-settings-dto.ts

- select pagingMode
- select unit_navibuttons

Add booklet config to unit download

---

docker-compose.override.yml
docker-compose.prod.yml

- Change path of exiting backend volume for production

Define docker volumes for backend

---

apps/api/src/app/database/services/resource-package.service.ts
apps/frontend/src/app/admin/resource-packages/resource-packages-table/resource-packages-table.component.html
package.json

- The name of the folder is the name of the file without the
extension "itcr.zip".
- Prohibit uploading packages with the same name

Unzip resource packages into their own folder

---

apps/api/src/app/admin/admin.module.ts
apps/api/src/app/admin/settings/setting.controller.ts
apps/api/src/app/app-version.guard.ts
apps/api/src/app/app.controller.ts
apps/api/src/app/app.module.ts
apps/api/src/main.ts
apps/frontend/src/app/auth.interceptor.ts
apps/frontend/src/assets/i18n/de.json
apps/frontend/src/main.ts
package.json

Guard some endpoints to ensure that backup and frontend versions do not differ

Check version

---

apps/api/src/app/database/services/workspace.service.ts
apps/api/src/app/workspace/unit-download.class.ts
apps/api/src/app/workspace/unit-import-data.class.ts
libs/shared-code/src/index.ts
libs/shared-code/src/lib/helper/verona-variable.class.ts

This changes version to 2.1.0-rc3

Extend unit xml import and export

---

apps/api/src/app/app-version.guard.ts
apps/frontend/src/app/workspace/backend.service.ts
apps/frontend/src/app/workspace/unit/unit-metadata/unit-metadata.component.html
apps/frontend/src/app/workspace/unit/unit-metadata/unit-metadata.component.ts
apps/frontend/src/app/workspace/workspace.component.html
apps/frontend/src/app/workspace/workspace.component.ts
apps/frontend/src/assets/i18n/de.json
apps/frontend/src/main.ts
package.json

- tab headers disabled
- if invalid path: unit id -> 0

Hide unit tabs if no unit selected

---

LICENSE
README.md
apps/api/src/app/app-version.guard.ts
apps/frontend/src/main.ts
package.json

Set version to 2.2.0

---

angular.json
apps/api/custom-webpack.config.js
apps/api/src/app/app-version.guard.ts
apps/frontend/src/main.ts
package-lock.json
package.json

- disable minimization for api (webpack config)

Set version to 2.2.1-rc.4

---

apps/api/src/app/app-version.guard.ts
apps/api/src/app/database/entities/resource-package.entity.ts
apps/api/src/app/database/entities/review-unit.entity.ts
apps/api/src/app/database/entities/review.entity.ts
apps/api/src/app/database/entities/setting.entity.ts
apps/api/src/app/database/entities/unit-comment.entity.ts
apps/api/src/app/database/entities/unit-definition.entity.ts
apps/api/src/app/database/entities/unit-user.entity.ts
apps/api/src/app/database/entities/unit.entity.ts
apps/api/src/app/database/entities/user.entity.ts
apps/api/src/app/database/entities/verona-module.entity.ts
apps/api/src/app/database/entities/workspace-group-admin.entity.ts
apps/api/src/app/database/entities/workspace-group.entity.ts
apps/api/src/app/database/entities/workspace-user.entity.ts
apps/api/src/app/database/entities/workspace.entity.ts
apps/frontend/src/main.ts
package.json

Add typeorm entities options

---

apps/frontend/src/app/workspace/components/add-unit-button/add-unit-button.component.spec.ts
apps/frontend/src/app/workspace/components/delete-unit-button/delete-unit-button.component.html
apps/frontend/src/app/workspace/components/delete-unit-button/delete-unit-button.component.spec.ts
apps/frontend/src/app/workspace/components/edit-unit-button/edit-unit-button.component.html
apps/frontend/src/app/workspace/components/edit-unit-button/edit-unit-button.component.spec.ts
apps/frontend/src/assets/i18n/de.json

Fix test for AddUnitButtonComponent

Add translations to unit crud buttons

---

apps/api/src/app/database/services/workspace.service.ts

The bug in the method was caused by the additional return value of the number of units

[backend] Fix method to find all workspaces

---

.gitlab-ci/Branch&PreRelease-Pipelines.gitlab-ci.yml
.gitlab-ci/Release-Pipelines.gitlab-ci.yml

https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5590

Use host network for docker build

---

apps/api/src/app/workspace/unit-download.class.ts

Wait until these fields are part of
https://raw.githubusercontent.com/iqb-berlin/testcenter-backend/master/definitions/vo_Unit.xsd

[backend] Remove transcript, reference metadata from xml export

---

apps/frontend/src/app/modules/workspace/components/add-unit-button/add-unit-button.component.ts
apps/frontend/src/app/modules/workspace/components/delete-unit-button/delete-unit-button.component.ts
apps/frontend/src/app/modules/workspace/components/select-unit-list/select-unit-list.component.ts
apps/frontend/src/app/modules/workspace/components/select-unit/select-unit.component.html
apps/frontend/src/app/modules/workspace/components/select-unit/select-unit.component.ts
apps/frontend/src/app/modules/workspace/components/units-area/units-area.component.html

Mark selected unit in add and delete dialog

---

apps/frontend/src/app/modules/admin/components/edit-user/edit-user.component.html

Not autocomplete password

---

apps/frontend/src/app/modules/workspace/components/booklet-config-edit/booklet-config-edit.component.html

Give labels and empty options to mat-select fields in booklet config

---

apps/frontend/src/app/modules/workspace/components/unit-selection/unit-selection.component.html
apps/frontend/src/app/modules/workspace/components/unit-table/unit-table.component.html
apps/frontend/src/app/modules/workspace/components/unit-table/unit-table.component.ts
apps/frontend/src/app/modules/workspace/components/workspace/workspace.component.ts
apps/frontend/src/app/modules/workspace/pipes/get-state-color.pipe.ts
apps/frontend/src/app/modules/workspace/services/workspace.service.ts

[frontend] Remove multiple backend accesses to display the unit's status

---

apps/frontend/src/app/modules/workspace/components/preview-bar/preview-bar.component.html

Show paging mode selection always

---

apps/frontend/src/app/modules/shared/components/profiles/profiles.component.ts

[frontend] Fix configuration of metadata profiles for workspace groups

---

apps/frontend/src/app/modules/workspace/components/unit-properties/unit-properties.component.ts

[frontend] Fix moving units to another workspace

---

apps/api/src/app/database/services/unit.service.ts

[api] Add logging for retrieving the unit definition

---

apps/frontend/src/app/modules/workspace/classes/unit-definition-store.ts
apps/frontend/src/app/modules/workspace/classes/unit-metadata-store.ts
apps/frontend/src/app/modules/workspace/classes/unit-scheme-store.ts
apps/frontend/src/app/modules/workspace/components/unit-save-button/unit-save-button.component.ts
apps/frontend/src/app/modules/workspace/services/workspace.service.ts

[frontend] Remove function call in template of UnitSaveButtonComponent

---

apps/frontend/src/app/modules/workspace/components/unit-save-button/unit-save-button.component.html

[frontend] Replace function call in template with property

---

apps/frontend/src/app/modules/comments/components/comment-editor/comment-editor.component.scss
apps/frontend/src/app/modules/comments/components/comment/comment.component.scss

[frontend] Disable word break in comments

---

apps/frontend/src/app/modules/workspace/components/edit-unit-button/edit-unit-button.component.ts

#439
- This removes the incorrect link in the address line

[frontend] Deselect current unit when moving units

---

apps/frontend/src/app/modules/workspace/components/unit-preview/unit-preview.component.ts
apps/frontend/src/app/modules/workspace/components/unit-schemer/unit-schemer.component.ts
apps/frontend/src/app/modules/workspace/services/workspace.service.ts

- This property is a duplicate of the property codingSchemer

[frontend] Remove unnecessary prop codingScheme from WorkspaceService

---

apps/api/src/app/database/services/unit.service.ts
libs/api-dto/src/lib/dto/unit/create-unit-dto.ts

[backend] Duplicate all unit properties when copying a unit

---

package-lock.json
package.json

Update version npm package @iqb/responses

---

apps/frontend/src/app/modules/metadata/components/item/item.component.ts

Remove debug field for fixed ID from metadata item form

---

apps/api/src/app/controllers/admin-workspace-group.controller.ts
apps/frontend/src/app/modules/admin/services/backend.service.ts

- Fix api tags for admin workspace-group

Change endpoint for deleting workspace-groups

---

apps/api/src/app/services/users.service.ts

Fix type confusion through parameter tampering

---

apps/frontend/src/app/modules/metadata/components/items/items.component.html

- add missing binding of variables

Fix the display of changed variableId in read-only mode (2)
